### ISSUE TITLE
The player freezes

### ISSUE THREAD

**Issue by naissa12** [AhmadAmri/AQPlayer#4]
When I listen to audio and slide the progress bar to the end, the player freezes. I can no longer press the play button to play. Can someone please fix this?

**Comment by AhmadAmri** [comment]
Does this happen when you reach the end of the last item? 
I guess you can use the status update delegate to move the player back to the first item.

**Comment by naissa12** [comment]
Can you send me the code to fix that?

**Comment by naissa12** [comment]
It happens when it reaches the end of each item

**Comment by naissa12** [comment]
I have another issue where i try to play the player and it gets stuck in loading or none status.

**Comment by AhmadAmri** [comment]
I'll try to find some time to check these issues !

Meanwhile double check that the player items are exist and you can play them; the example is just a show case without much validation !

**Comment by AhmadAmri** [comment]
Changing how manage the playlist and player status should fix the issue.
